### ISSUE TITLE
Minor docstring issue

### ISSUE THREAD

**Issue by ablaom** [john-waczak/SelfOrganizingMaps.jl#17]
The "grid_type" should be surrounded in single back quotes as the underscore is messing with formatting:

https://github.com/john-waczak/SelfOrganizingMaps.jl/blob/ef57bd0884ec443598eca4190a0f51213722305c/src/SelfOrganizingMaps.jl#L138

**Comment by john-waczak** [comment]
@ablaom  Fixed!
